### ISSUE TITLE
Provide specific guidance on embedding metadata for spreadsheets

### ISSUE THREAD

**Issue by jqnatividad** [DOI-DO/dcat-us#130]
**Creator Name:** Joel Natividad
**Creator Affiliation:** datHere, Inc.

## Requirement(s)

A lot of data is distributed and consumed as spreadsheets. Spreadsheet software like Excel and Apache OpenOffice both support mechanisms for embedding metadata as part of their file formats (In both systems, by going to File Properties)

It'd be great if DCAT metadata can be embedded in the spreadsheet as standard practice.

Further, in addition to the DCAT metadata, a link back to the Catalog entry of the dataset from where the dataset was downloaded will help users not only track the provenance of the data, but also, redownload it if required.

## Problem Statement

Though all spreadsheet software have this metadata embedding mechanism, it is hardly used.

## Target Audience / Stakeholders

Everyone.

## Intended Uses / Use Cases

* Data Catalog systems can automatically use the spreadsheet's File Properties to:
  - prepopulate metadata fields as part of dataset onboarding if a spreadsheet with embedded metadata is registered
  - to optionally embed the current metadata when downloading/exporting spreadsheets
* Users of the spreadsheet can quickly retrieve the metadata from the spreadsheet itself, and if need be, follow the link to the Catalog from where the spreadsheet was distributed/exported

**Comment by fellahst** [comment]
Joel,

Thank you for your proposal regarding the embedding of DCAT metadata within spreadsheet files such as those created in Excel or Apache OpenOffice. While embedding metadata directly into spreadsheets can enhance data traceability and provenance, it's important to note that the core function of DCAT-US is to define a model for dataset metadata in a way that is independent of the data format.

The practice of embedding DCAT metadata into spreadsheets, though beneficial, extends beyond the scope of DCAT-US as a metadata standard. DCAT-US is designed to be format-agnostic, focusing on the structure and specification of metadata for datasets rather than the mechanisms for embedding this metadata into specific file types. However, the metadata defined by DCAT-US can indeed be used as a reference for the metadata that might be embedded in spreadsheets.

Your point about the underutilization of metadata embedding capabilities in spreadsheet software is well-taken and highlights a broader issue in data management practices. While DCAT-US may not directly address this practice, it certainly provides a robust framework that can inform and guide the metadata content to be embedded in such files.
