### ISSUE TITLE
Provide guidance for publishing documents in PDF format in accordance with NARA standards/mandates

### ISSUE THREAD

**Issue by jqnatividad** [DOI-DO/dcat-us#133]
**Creator Name:** Joel Natividad
**Creator Affiliation:** datHere, Inc.

## Requirement(s)

The PDF file format is an ubiquitous format.  So much so that what started out as a proprietary data format is now an ISO Standard - [ISO 3200-2](https://www.pdfa.org/sponsored-standards).

Further, in connection with NARA [88 FR 28417](https://www.federalregister.gov/citation/88-FR-28417) Rule effective June 5, 2023 - there is specific guidance in publishing federal records as PDF/A (PDF Archival format) in a standard, machine-readable manner that speaks specifically to embedded metadata requirements:

https://www.federalregister.gov/documents/2023/05/04/2023-09050/federal-records-management-digitizing-permanent-records-and-reviewing-records-schedules#sectno-citation-1236.54

It'd be great if DCAT-US 3.0 is aligned with metadata requirements of the NARA standard.

## Problem Statement

PDFs are widely distributed in Data Catalogs. Our experience in our data catalog implementations however has shown that there are no existing standards when publishing PDFs.

There is hardly no metadata, and even some PDFs which should be text-selectable are often published as images.  Sometimes, even tabular data is published as image PDFs, most prevalently with financial reports (Budget Books).

The NARA Rule referenced above should help improve the situation.

Aligning DCAT-US 3.0 with the NARA metadata requirements should help accelerate the adoption of both DCAT-US 3.0 and the NARA ruling.

## Target Audience / Stakeholders

Everyone.

## Intended Uses / Use Cases

* Data Catalog Systems can read the embedded metadata in PDFs and prepopulate metadata fields, easing the work of the Data Publisher and minimizing metadata-entry errors when publishing PDF files
* Data Catalog Systems often ingest PDF content to populate the Catalog's search index. Having standardized machine-readable metadata in the PDF should improve search results, increasing Findability.

## Additional context, comments, or links

There is an excellent blogpost published by the NARA Electronic Records Policy and Standards Team Oct 26, 2023 on "The US Government's Transition to All-Digital Government."

https://pdfa.org/the-u-s-governments-transition-to-all-digital-government/
https://records-express.blogs.archives.gov/2023/06/12/digitizing-records-understanding-metadata-requirements/

**Comment by hkdctol** [comment]
Anyone on core team have background on this?

**Comment by fellahst** [comment]
Joel,

Thank you for your suggestion regarding the alignment of DCAT-US 3.0 with NARA's metadata requirements for PDF files. While the standardization of PDF metadata is valuable, it's important to clarify that DCAT-US primarily defines the model for dataset metadata and remains format-agnostic. The extraction of metadata from PDFs falls outside the scope of DCAT-US, as it pertains to the development of tools for metadata extraction rather than the specification of the metadata model itself. However, extracted metadata can certainly be mapped to the DCAT-US model, offering flexibility in accommodating various data formats while maintaining the focus on dataset metadata structure.
