### ISSUE TITLE
High Value Asset Designation

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#26]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *(tbd - identification of asset as High Value Asset)*
Priority: *High*
Element Description / Requirement / Recommendation
Agency High Value Assets (HVAs): Submitted to OMB, DHS, and GAO under the Federal Information Security Modernization Act (FISMA) may provide additional contextual information for metadata.  required

## Problem Statement
FISMA requirement

## Target Audience / Stakeholders
Data owners, auditors

## Intended Uses / Use Cases
Identifying high value assets

## Additional context, comments, or links
FISMA

**Comment by fellahst** [comment]
David,

Thank you for your submission regarding the proposed element of identifying assets as High Value Assets (HVAs) under the Federal Information Security Modernization Act (FISMA). We recognize the importance of this element in the context of data security and management, especially for data owners and auditors.

However, after careful consideration, we have recommended that this particular suggestion falls outside the scope of our current project. In the United States, the term "HVA" predominantly applies to systems rather than datasets. The designation of HVAs in the U.S. carries a narrower security meaning, primarily focusing on controlled classified information.

For a broader perspective on handling high-value datasets, we recommend reviewing the European DCAT-AP High Value Datasets profile. The European approach provides a comprehensive framework for categorizing and handling high-value datasets, which might offer valuable insights and alternative methodologies. You can find more information about this approach at [DCAT-AP High Value Datasets profile](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd).

We encourage you to continue sharing your valuable insights and suggestions.

**Comment by ShaferAC** [comment]
+1

**Comment by mrratcliffe** [comment]
+1
